version: '3.8'

services:
  recommender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommender
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped

